### ISSUE TITLE
reduce the number of dependencies

### ISSUE THREAD

**Issue by phobson** [phobson/pygridtools#30]
per @ocefpaf.

Hey Filipe: I've got a few cycles available for me to spend on pygridtools. Feel free to file any other issues you might have.

**Comment by ocefpaf** [comment]
I did not get as enough time to play with `pygridtools` yet, but so far it seemed pretty solid and no issue comes to mind.

The number of optional deps is not a real issue BTW, but it does make packaging a lot easier.
